basePath: /
definitions:
  dbmodels.WithdrawalKind:
    enum:
    - custom
    - eth
    - erc20
    - erc721
    - erc1155
    type: string
    x-enum-varnames:
    - CustomWithdrawal
    - ETHWithdrawal
    - ERC20Withdrawal
    - ERC721Withdrawal
    - ERC1155Withdrawal
  dbmodels.WithdrawalStatus:
    enum:
    - initiated
    - proven
    - finalized_successful
    - finalized_failed
    type: string
    x-enum-varnames:
    - WithdrawalInitiated
    - WithdrawalProven
    - WithdrawalFinalizedSuccess
    - WithdrawalFinalizedFail
  response.ErrorEnvelope:
    properties:
      error:
        type: string
    type: object
  withdrawals.EnvelopedWithdrawalHistoryResponse:
    properties:
      message:
        type: string
      result:
        properties:
          address:
            type: string
          source_chain_id:
            type: integer
          total_count:
            type: integer
          withdrawals:
            items:
              properties:
                amount:
                  type: string
                block_number:
                  type: integer
                block_timestamp:
                  type: integer
                chain_id:
                  type: integer
                decoded_action:
                  type: string
                from_address:
                  type: string
                kind:
                  $ref: '#/definitions/dbmodels.WithdrawalKind'
                status:
                  $ref: '#/definitions/dbmodels.WithdrawalStatus'
                to_address:
                  type: string
                token_address:
                  type: string
                token_chain_id:
                  type: integer
                token_class:
                  type: string
                token_decimals:
                  type: integer
                token_id:
                  type: string
                token_name:
                  type: string
                token_symbol:
                  type: string
                tx_hash:
                  type: string
                withdrawal_data:
                  type: string
                withdrawal_gas_limit:
                  type: string
                withdrawal_hash:
                  type: string
                withdrawal_nonce:
                  type: string
                withdrawal_sender:
                  type: string
                withdrawal_target:
                  type: string
                withdrawal_value:
                  type: string
              type: object
            type: array
        type: object
    type: object
info:
  contact: {}
  description: Frontend API service for OP withdrawals indexer
  title: OP Withdrawals Indexer API
  version: "1.0"
paths:
  /withdrawal-history:
    get:
      consumes:
      - application/json
      description: |-
        Returns a list of withdrawals of a chain id initiated by an Ethereum address or proven by it.
        Withdrawals are fetched in latest-first order.
        Paginated query, with batches of 25.
      parameters:
      - description: Ethereum address
        in: query
        name: address
        required: true
        type: string
      - description: Chain id of withdrawal initiation transaction
        in: query
        name: chain_id
        required: true
        type: integer
      - description: Page number for pagination
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/withdrawals.EnvelopedWithdrawalHistoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorEnvelope'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorEnvelope'
      summary: Get withdrawals history related to an address
      tags:
      - withdrawals
swagger: "2.0"
